var countriesList = [
    {countryName: "Австралия", countryCode: "AU", countryType: 1},
    {countryName: "Австрия", countryCode: "AT", countryType: 0},
    {countryName: "Азербайджан", countryCode: "AZ", countryType: 1},
    {countryName: "Аландские о-ва", countryCode: "AX", countryType: 1},
    {countryName: "Албания", countryCode: "AL", countryType: 1},
    {countryName: "Алжир", countryCode: "DZ", countryType: 1},
    {countryName: "Американское Самоа", countryCode: "AS", countryType: 1},
    {countryName: "Ангилья", countryCode: "AI", countryType: 1},
    {countryName: "Ангола", countryCode: "AO", countryType: 1},
    {countryName: "Андорра", countryCode: "AD", countryType: 0},
    {countryName: "Антарктида", countryCode: "AQ", countryType: 1},
    {countryName: "Антигуа и Барбуда", countryCode: "AG", countryType: 1},
    {countryName: "Аргентина", countryCode: "AR", countryType: 1},
    {countryName: "Армения", countryCode: "AM", countryType: 1},
    {countryName: "Аруба", countryCode: "AW", countryType: 1},
    {countryName: "Афганистан", countryCode: "AF", countryType: 1},
    {countryName: "Багамские о-ва", countryCode: "BS", countryType: 1},
    {countryName: "Бангладеш", countryCode: "BD", countryType: 1},
    {countryName: "Барбадос", countryCode: "BB", countryType: 1},
    {countryName: "Бахрейн", countryCode: "BH", countryType: 1},
    {countryName: "Беларусь", countryCode: "BY", countryType: 1},
    {countryName: "Белиз", countryCode: "BZ", countryType: 1},
    {countryName: "Бельгия", countryCode: "BE", countryType: 0},
    {countryName: "Бенин", countryCode: "BJ", countryType: 1},
    {countryName: "Бермудские о-ва", countryCode: "BM", countryType: 1},
    {countryName: "Болгария", countryCode: "BG", countryType: 1},
    {countryName: "Боливия", countryCode: "BO", countryType: 1},
    {countryName: "Бонэйр, Синт-Эстатиус и Саба", countryCode: "BQ", countryType: 1},
    {countryName: "Босния и Герцеговина", countryCode: "BA", countryType: 1},
    {countryName: "Ботсвана", countryCode: "BW", countryType: 1},
    {countryName: "Бразилия", countryCode: "BR", countryType: 1},
    {countryName: "Британская территория в Индийском океане", countryCode: "IO", countryType: 1},
    {countryName: "Бруней-Даруссалам", countryCode: "BN", countryType: 1},
    {countryName: "Буркина-Фасо", countryCode: "BF", countryType: 1},
    {countryName: "Бурунди", countryCode: "BI", countryType: 1},
    {countryName: "Бутан", countryCode: "BT", countryType: 1},
    {countryName: "Вануату", countryCode: "VU", countryType: 1},
    {countryName: "Ватикан", countryCode: "VA", countryType: 1},
    {countryName: "Великобритания", countryCode: "GB", countryType: 0},
    {countryName: "Венгрия", countryCode: "HU", countryType: 1},
    {countryName: "Венесуэла", countryCode: "VE", countryType: 1},
    {countryName: "Виргинские о-ва (Британские)", countryCode: "VG", countryType: 1},
    {countryName: "Виргинские о-ва (США)", countryCode: "VI", countryType: 1},
    {countryName: "Внешние малые о-ва (США)", countryCode: "UM", countryType: 1},
    {countryName: "Восточный Тимор", countryCode: "TL", countryType: 1},
    {countryName: "Вьетнам", countryCode: "VN", countryType: 1},
    {countryName: "Габон", countryCode: "GA", countryType: 1},
    {countryName: "Гаити", countryCode: "HT", countryType: 1},
    {countryName: "Гайана", countryCode: "GY", countryType: 1},
    {countryName: "Гамбия", countryCode: "GM", countryType: 1},
    {countryName: "Гана", countryCode: "GH", countryType: 1},
    {countryName: "Гваделупа", countryCode: "GP", countryType: 1},
    {countryName: "Гватемала", countryCode: "GT", countryType: 1},
    {countryName: "Гвинея", countryCode: "GN", countryType: 1},
    {countryName: "Гвинея-Бисау", countryCode: "GW", countryType: 1},
    {countryName: "Германия", countryCode: "DE", countryType: 0},
    {countryName: "Гернси", countryCode: "GG", countryType: 1},
    {countryName: "Гибралтар", countryCode: "GI", countryType: 1},
    {countryName: "Гондурас", countryCode: "HN", countryType: 1},
    {countryName: "Гонконг (особый район)", countryCode: "HK", countryType: 1},
    {countryName: "Гренада", countryCode: "GD", countryType: 1},
    {countryName: "Гренландия", countryCode: "GL", countryType: 1},
    {countryName: "Греция", countryCode: "GR", countryType: 0},
    {countryName: "Грузия", countryCode: "GE", countryType: 1},
    {countryName: "Гуам", countryCode: "GU", countryType: 1},
    {countryName: "Дания", countryCode: "DK", countryType: 0},
    {countryName: "Джерси", countryCode: "JE", countryType: 1},
    {countryName: "Джибути", countryCode: "DJ", countryType: 1},
    {countryName: "Диего-Гарсия", countryCode: "DG", countryType: 1},
    {countryName: "Доминика", countryCode: "DM", countryType: 1},
    {countryName: "Доминиканская Республика", countryCode: "DO", countryType: 1},
    {countryName: "Египет", countryCode: "EG", countryType: 1},
    {countryName: "Замбия", countryCode: "ZM", countryType: 1},
    {countryName: "Западная Сахара", countryCode: "EH", countryType: 1},
    {countryName: "Зимбабве", countryCode: "ZW", countryType: 1},
    {countryName: "Израиль", countryCode: "IL", countryType: 0},
    {countryName: "Индия", countryCode: "IN", countryType: 1},
    {countryName: "Индонезия", countryCode: "ID", countryType: 1},
    {countryName: "Иордания", countryCode: "JO", countryType: 1},
    {countryName: "Ирак", countryCode: "IQ", countryType: 1},
    {countryName: "Иран", countryCode: "IR", countryType: 1},
    {countryName: "Ирландия", countryCode: "IE", countryType: 0},
    {countryName: "Исландия", countryCode: "IS", countryType: 0},
    {countryName: "Испания", countryCode: "ES", countryType: 0},
    {countryName: "Италия", countryCode: "IT", countryType: 0},
    {countryName: "Йемен", countryCode: "YE", countryType: 1},
    {countryName: "Кабо-Верде", countryCode: "CV", countryType: 1},
    {countryName: "Казахстан", countryCode: "KZ", countryType: 1},
    {countryName: "Каймановы о-ва", countryCode: "KY", countryType: 1},
    {countryName: "Камбоджа", countryCode: "KH", countryType: 1},
    {countryName: "Камерун", countryCode: "CM", countryType: 1},
    {countryName: "Канада", countryCode: "CA", countryType: 1},
    {countryName: "Канарские о-ва", countryCode: "IC", countryType: 1},
    {countryName: "Катар", countryCode: "QA", countryType: 1},
    {countryName: "Кения", countryCode: "KE", countryType: 1},
    {countryName: "Кипр", countryCode: "CY", countryType: 0},
    {countryName: "Киргизия", countryCode: "KG", countryType: 1},
    {countryName: "Кирибати", countryCode: "KI", countryType: 1},
    {countryName: "Китай", countryCode: "CN", countryType: 1},
    {countryName: "КНДР", countryCode: "KP", countryType: 1},
    {countryName: "Кокосовые о-ва", countryCode: "CC", countryType: 1},
    {countryName: "Колумбия", countryCode: "CO", countryType: 1},
    {countryName: "Коморские о-ва", countryCode: "KM", countryType: 1},
    {countryName: "Конго - Браззавиль", countryCode: "CG", countryType: 1},
    {countryName: "Конго - Киншаса", countryCode: "CD", countryType: 1},
    {countryName: "Косово", countryCode: "XK", countryType: 1},
    {countryName: "Коста-Рика", countryCode: "CR", countryType: 1},
    {countryName: "Кот-д’Ивуар", countryCode: "CI", countryType: 1},
    {countryName: "Куба", countryCode: "CU", countryType: 1},
    {countryName: "Кувейт", countryCode: "KW", countryType: 1},
    {countryName: "Кюрасао", countryCode: "CW", countryType: 1},
    {countryName: "Лаос", countryCode: "LA", countryType: 1},
    {countryName: "Латвия", countryCode: "LV", countryType: 1},
    {countryName: "Лесото", countryCode: "LS", countryType: 1},
    {countryName: "Либерия", countryCode: "LR", countryType: 1},
    {countryName: "Ливан", countryCode: "LB", countryType: 1},
    {countryName: "Ливия", countryCode: "LY", countryType: 1},
    {countryName: "Литва", countryCode: "LT", countryType: 1},
    {countryName: "Лихтенштейн", countryCode: "LI", countryType: 1},
    {countryName: "Люксембург", countryCode: "LU", countryType: 0},
    {countryName: "Маврикий", countryCode: "MU", countryType: 1},
    {countryName: "Мавритания", countryCode: "MR", countryType: 1},
    {countryName: "Мадагаскар", countryCode: "MG", countryType: 1},
    {countryName: "Майотта", countryCode: "YT", countryType: 1},
    {countryName: "Макао (особый район)", countryCode: "MO", countryType: 1},
    {countryName: "Македония", countryCode: "MK", countryType: 1},
    {countryName: "Малави", countryCode: "MW", countryType: 1},
    {countryName: "Малайзия", countryCode: "MY", countryType: 1},
    {countryName: "Мали", countryCode: "ML", countryType: 1},
    {countryName: "Мальдивские о-ва", countryCode: "MV", countryType: 1},
    {countryName: "Мальта", countryCode: "MT", countryType: 0},
    {countryName: "Марокко", countryCode: "MA", countryType: 1},
    {countryName: "Мартиника", countryCode: "MQ", countryType: 1},
    {countryName: "Маршалловы о-ва", countryCode: "MH", countryType: 1},
    {countryName: "Мексика", countryCode: "MX", countryType: 1},
    {countryName: "Мозамбик", countryCode: "MZ", countryType: 1},
    {countryName: "Молдова", countryCode: "MD", countryType: 1},
    {countryName: "Монако", countryCode: "MC", countryType: 0},
    {countryName: "Монголия", countryCode: "MN", countryType: 1},
    {countryName: "Монтсеррат", countryCode: "MS", countryType: 1},
    {countryName: "Мьянма (Бирма)", countryCode: "MM", countryType: 1},
    {countryName: "Намибия", countryCode: "NA", countryType: 1},
    {countryName: "Науру", countryCode: "NR", countryType: 1},
    {countryName: "Непал", countryCode: "NP", countryType: 1},
    {countryName: "Нигер", countryCode: "NE", countryType: 1},
    {countryName: "Нигерия", countryCode: "NG", countryType: 1},
    {countryName: "Нидерланды", countryCode: "NL", countryType: 0},
    {countryName: "Никарагуа", countryCode: "NI", countryType: 1},
    {countryName: "Ниуэ", countryCode: "NU", countryType: 1},
    {countryName: "Новая Зеландия", countryCode: "NZ", countryType: 1},
    {countryName: "Новая Каледония", countryCode: "NC", countryType: 1},
    {countryName: "Норвегия", countryCode: "NO", countryType: 0},
    {countryName: "о-в Вознесения", countryCode: "AC", countryType: 1},
    {countryName: "О-в Мэн", countryCode: "IM", countryType: 1},
    {countryName: "о-в Норфолк", countryCode: "NF", countryType: 1},
    {countryName: "о-в Рождества", countryCode: "CX", countryType: 1},
    {countryName: "О-в Св. Елены", countryCode: "SH", countryType: 1},
    {countryName: "о-ва Кука", countryCode: "CK", countryType: 1},
    {countryName: "О-ва Тёркс и Кайкос", countryCode: "TC", countryType: 1},
    {countryName: "ОАЭ", countryCode: "AE", countryType: 1},
    {countryName: "Оман", countryCode: "OM", countryType: 1},
    {countryName: "Пакистан", countryCode: "PK", countryType: 1},
    {countryName: "Палау", countryCode: "PW", countryType: 1},
    {countryName: "Палестинские территории", countryCode: "PS", countryType: 1},
    {countryName: "Панама", countryCode: "PA", countryType: 1},
    {countryName: "Папуа – Новая Гвинея", countryCode: "PG", countryType: 1},
    {countryName: "Парагвай", countryCode: "PY", countryType: 1},
    {countryName: "Перу", countryCode: "PE", countryType: 1},
    {countryName: "Питкэрн", countryCode: "PN", countryType: 1},
    {countryName: "Польша", countryCode: "PL", countryType: 1},
    {countryName: "Португалия", countryCode: "PT", countryType: 0},
    {countryName: "Пуэрто-Рико", countryCode: "PR", countryType: 1},
    {countryName: "Республика Корея", countryCode: "KR", countryType: 1},
    {countryName: "Реюньон", countryCode: "RE", countryType: 1},
    {countryName: "Россия", countryCode: "RU", countryType: 1},
    {countryName: "Руанда", countryCode: "RW", countryType: 1},
    {countryName: "Румыния", countryCode: "RO", countryType: 1},
    {countryName: "Сальвадор", countryCode: "SV", countryType: 1},
    {countryName: "Самоа", countryCode: "WS", countryType: 1},
    {countryName: "Сан-Марино", countryCode: "SM", countryType: 0},
    {countryName: "Сан-Томе и Принсипи", countryCode: "ST", countryType: 1},
    {countryName: "Саудовская Аравия", countryCode: "SA", countryType: 1},
    {countryName: "Свазиленд", countryCode: "SZ", countryType: 1},
    {countryName: "Северные Марианские о-ва", countryCode: "MP", countryType: 1},
    {countryName: "Сейшельские о-ва", countryCode: "SC", countryType: 1},
    {countryName: "Сен-Бартельми", countryCode: "BL", countryType: 1},
    {countryName: "Сен-Мартен", countryCode: "MF", countryType: 1},
    {countryName: "Сен-Пьер и Микелон", countryCode: "PM", countryType: 1},
    {countryName: "Сенегал", countryCode: "SN", countryType: 1},
    {countryName: "Сент-Винсент и Гренадины", countryCode: "VC", countryType: 1},
    {countryName: "Сент-Китс и Невис", countryCode: "KN", countryType: 1},
    {countryName: "Сент-Люсия", countryCode: "LC", countryType: 1},
    {countryName: "Сербия", countryCode: "RS", countryType: 1},
    {countryName: "Сеута и Мелилья", countryCode: "EA", countryType: 1},
    {countryName: "Сингапур", countryCode: "SG", countryType: 1},
    {countryName: "Синт-Мартен", countryCode: "SX", countryType: 1},
    {countryName: "Сирия", countryCode: "SY", countryType: 1},
    {countryName: "Словакия", countryCode: "SK", countryType: 1},
    {countryName: "Словения", countryCode: "SI", countryType: 0},
    {countryName: "Соединенные Штаты", countryCode: "US", countryType: 1},
    {countryName: "Соломоновы о-ва", countryCode: "SB", countryType: 1},
    {countryName: "Сомали", countryCode: "SO", countryType: 1},
    {countryName: "Судан", countryCode: "SD", countryType: 1},
    {countryName: "Суринам", countryCode: "SR", countryType: 1},
    {countryName: "Сьерра-Леоне", countryCode: "SL", countryType: 1},
    {countryName: "Таджикистан", countryCode: "TJ", countryType: 1},
    {countryName: "Таиланд", countryCode: "TH", countryType: 1},
    {countryName: "Тайвань", countryCode: "TW", countryType: 1},
    {countryName: "Танзания", countryCode: "TZ", countryType: 1},
    {countryName: "Того", countryCode: "TG", countryType: 1},
    {countryName: "Токелау", countryCode: "TK", countryType: 1},
    {countryName: "Тонга", countryCode: "TO", countryType: 1},
    {countryName: "Тринидад и Тобаго", countryCode: "TT", countryType: 1},
    {countryName: "Тристан-да-Кунья", countryCode: "TA", countryType: 1},
    {countryName: "Тувалу", countryCode: "TV", countryType: 1},
    {countryName: "Тунис", countryCode: "TN", countryType: 1},
    {countryName: "Туркменистан", countryCode: "TM", countryType: 1},
    {countryName: "Турция", countryCode: "TR", countryType: 1},
    {countryName: "Уганда", countryCode: "UG", countryType: 1},
    {countryName: "Узбекистан", countryCode: "UZ", countryType: 1},
    {countryName: "Украина", countryCode: "UA", countryType: 1},
    {countryName: "Уоллис и Футуна", countryCode: "WF", countryType: 1},
    {countryName: "Уругвай", countryCode: "UY", countryType: 1},
    {countryName: "Фарерские о-ва", countryCode: "FO", countryType: 1},
    {countryName: "Федеративные Штаты Микронезии", countryCode: "FM", countryType: 1},
    {countryName: "Фиджи", countryCode: "FJ", countryType: 1},
    {countryName: "Филиппины", countryCode: "PH", countryType: 1},
    {countryName: "Финляндия", countryCode: "FI", countryType: 0},
    {countryName: "Фолклендские о-ва", countryCode: "FK", countryType: 1},
    {countryName: "Франция", countryCode: "FR", countryType: 0},
    {countryName: "Французская Гвиана", countryCode: "GF", countryType: 1},
    {countryName: "Французская Полинезия", countryCode: "PF", countryType: 1},
    {countryName: "Французские Южные Территории", countryCode: "TF", countryType: 1},
    {countryName: "Хорватия", countryCode: "HR", countryType: 1},
    {countryName: "ЦАР", countryCode: "CF", countryType: 1},
    {countryName: "Чад", countryCode: "TD", countryType: 1},
    {countryName: "Черногория", countryCode: "ME", countryType: 1},
    {countryName: "Чехия", countryCode: "CZ", countryType: 1},
    {countryName: "Чили", countryCode: "CL", countryType: 0},
    {countryName: "Швейцария", countryCode: "CH", countryType: 0},
    {countryName: "Швеция", countryCode: "SE", countryType: 1},
    {countryName: "Шпицберген и Ян-Майен", countryCode: "SJ", countryType: 1},
    {countryName: "Шри-Ланка", countryCode: "LK", countryType: 1},
    {countryName: "Эквадор", countryCode: "EC", countryType: 1},
    {countryName: "Экваториальная Гвинея", countryCode: "GQ", countryType: 1},
    {countryName: "Эритрея", countryCode: "ER", countryType: 1},
    {countryName: "Эстония", countryCode: "EE", countryType: 1},
    {countryName: "Эфиопия", countryCode: "ET", countryType: 1},
    {countryName: "ЮАР", countryCode: "ZA", countryType: 1},
    {countryName: "Южная Георгия и Южные Сандвичевы о-ва", countryCode: "GS", countryType: 1},
    {countryName: "Южный Судан", countryCode: "SS", countryType: 1},
    {countryName: "Ямайка", countryCode: "JM", countryType: 1},
    {countryName: "Япония", countryCode: "JP", countryType: 1}
];

export default countriesList;